### ISSUE TITLE
Cannot download NARR data onto my computer

### ISSUE THREAD

**Issue by apalipana91** [geomarker-io/addNarrData#7]
Hi,

I tried to download NARR data for the first time using download_narr_fst() on R. But, the download process kept restarting. Then I tried using https://geomarker.s3.us-east-2.amazonaws.com/narr/narr.fst to download the data. The download gets interrupted halfway.

Thanks!

**Comment by cole-brokamp** [comment]
Do you think its possible that it is related to your internet connection? If downloading outside of R directly from the https site, then I think the problem is not related to the package.  

One good way to download large data from a spotty internet connection is to resume broken downloads using `wget` by passing the continue option.  In a shell, you could try `wget -c https://geomarker.s3.us-east-2.amazonaws.com/narr/narr.fst` to download the file into the working directory and then manually place it into the Application Data folder where the package is expecting it.

**Comment by apalipana91** [comment]
Hi Cole,

I tried what you suggested. Now, the example code given in https://geomarker.io/addNarrData/ runs well and I get the expected output. Thanks!

**Comment by cole-brokamp** [comment]
Great, thanks!  This is still helpful to know.  We are going to work on better and more reliable ways to download the necessary files for this package.
